import { type Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}
const isClient = () => typeof window !== 'undefined';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>)

{
  if (isClient()) {
    // Safe to use `document` here
    console.log(document.title);
  }
  return (
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
          <header className="">
          </header>
          {children}
        </body>
      </html>
  )
}